---
- hosts: ubuntu
  become: yes
  tasks:
  - name: Type Zabbix server
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      line: "{{ item.line }}"
      regexp: "{{ item.regexp }}"
    loop:
      - regexp: '^Server='
        line: 'Server=10.128.0.6'
      - regexp: '^ServerActive='
        line: 'ServerActive=10.128.0.6'
#     - regexp: '^# Hostname='
#       line: 'Hostname={{ ansible_hostname }}'
